5gnidd:
  AE:
    compression_factor: 2
    lr: 0.01
    n_epochs: 5
    reg: 0.6244000080513158
  DeepSVDD:
    lr: 0.0001
    n_epochs: 5
unswnb15:
  AE:
    compression_factor: 4
    lr: 1.0e-05
    n_epochs: 95
    reg: 0.8975025223445524
  DeepSVDD:
    lr: 0.001
    n_epochs: 5
